version: '3.8'

services:
  ffc-sfi-apply-api:
    build:
      context: .
      target: production
    image: ffc-sfi-apply-api
    container_name: ffc-sfi-apply-api
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-apply-api-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      ELIGIBILITY_TOPIC_ADDRESS: ${ELIGIBILITY_TOPIC_ADDRESS:-notset}
      ELIGIBILITY_SUBSCRIPTION_ADDRESS: ${ELIGIBILITY_SUBSCRIPTION_ADDRESS:-notset}
      STANDARDS_SUBSCRIPTION_ADDRESS: ${STANDARDS_SUBSCRIPTION_ADDRESS:-notset}
      STANDARDS_TOPIC_ADDRESS: ${STANDARDS_TOPIC_ADDRESS:-notset}
      VALIDATE_SUBSCRIPTION_ADDRESS: ${VALIDATE_SUBSCRIPTION_ADDRESS:-notset}
      VALIDATE_TOPIC_ADDRESS: ${VALIDATE_TOPIC_ADDRESS:-notset}
      CALCULATE_SUBSCRIPTION_ADDRESS: ${CALCULATE_SUBSCRIPTION_ADDRESS:-notset}
      CALCULATE_TOPIC_ADDRESS: ${CALCULATE_TOPIC_ADDRESS:-notset}
      SUBMIT_SUBSCRIPTION_ADDRESS: ${SUBMIT_SUBSCRIPTION_ADDRESS:-notset}
      SUBMIT_TOPIC_ADDRESS: ${SUBMIT_TOPIC_ADDRESS:-notset}
      REDIS_HOSTNAME: redis
