apiVersion: v2
description: FFC apply for SFI API back end
name: ffc-sfi-apply-api
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^2.11.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
