environment: development
name: ffc-sfi-apply-api
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-apply-api

labels: {}

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-apply-api-config-map

containerSecret:
  name: ffc-sfi-apply-api-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3001
  messageQueueHost: amq
  eligibilitySubscriptionAddress: ffc-sfi-eligibility-check-api
  standardsSubscriptionAddress: ffc-sfi-standards-request-api
  validateSubscriptionAddress: ffc-sfi-agreement-validate-api
  submitSubscriptionAddress: ffc-sfi-agreement-submit-api
  calculateSubscriptionAddress: ffc-sfi-agreement-calculate-api
  eligibilityTopicAddress: ffc-sfi-eligibility-check
  standardsTopicAddress: ffc-sfi-standards-request
  validateTopicAddress: ffc-sfi-agreement-validate
  submitTopicAddress: ffc-sfi-agreement-submit
  calculateTopicAddress: ffc-sfi-agreement-calculate
  agreementCalculatorEndpoint: http://ffc-sfi-siti-agri-mock.ffc-sfi
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-sfi-apply-api

livenessProbe:
  path: /healthz
  port: 3001
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3001
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

appInsights:
  key:
    
aadPodIdentity: true
