environment: development
name: ffc-sfi-apply-api
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-apply-api

labels: {}

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-apply-api-config-map

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  messageQueueHost: amq
  eligibilitySubscriptionAddress: eligibility
  standardsSubscriptionAddress: standards
  validateSubscriptionAddress: validate
  submitSubscriptionAddress: submit
  calculateSubscriptionAddress: calculate
  eligibilityTopicAddress: eligibility
  standardsTopicAddress: standards
  validateTopicAddress: validate
  submitTopicAddress: submit
  calculateTopicAddress: calculate

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

appInsights:
  key:appInsights:
  key:
    
aadPodIdentity: true